//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskRegMgmtASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESKREG_VLAN
    {
        public int VLAN_ID { get; set; }
        public string VLAN_NAME { get; set; }
        public Nullable<int> VLAN_NO { get; set; }
        public string VLAN_SHOW { get; set; }
    }
}
