//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskRegMgmtASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESKREG_USERINFO
    {
        public string UNIQUE_ID { get; set; }
        public string USER_LNAME { get; set; }
        public string USER_FNAME { get; set; }
        public string DISABLED { get; set; }
        public string USERID { get; set; }
    }
}
