//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskRegMgmtASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class EchoAppAdmin
    {
        public int AdminID { get; set; }
        public int ApplicationID { get; set; }
        public string ColleagueID { get; set; }
    }
}
